version: '3.8'

services:
  evawova-zookeeper-1:
    image: confluentinc/cp-zookeeper:7.2.6
    ports:
      - '32181:32181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - evawova-network
  evawova-kafka-1:
    image: confluentinc/cp-kafka:7.2.6
    ports:
      - '9092:9092'
    depends_on:
      - evawova-zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: evawova-zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://evawova-kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - evawova-network
  evawova-kafka-2:
    image: confluentinc/cp-kafka:7.2.6
    ports:
      - '9093:9093'
    depends_on:
      - evawova-zookeeper-1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: evawova-zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://evawova-kafka-2:29093,EXTERNAL://localhost:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - evawova-network
  evawova-kafka-3:
    image: confluentinc/cp-kafka:7.2.6
    ports:
      - '9094:9094'
    depends_on:
      - evawova-zookeeper-1
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: evawova-zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://evawova-kafka-3:29094,EXTERNAL://localhost:9094
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - evawova-network
  evawova-kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: evawova-kafka-ui
    ports:
      - '9000:8080'
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=evawova-local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=evawova-kafka-1:29092,evawova-kafka-2:29093,evawova-evawova-kafka-3:29094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=evawova-zookeeper-1:22181
    networks:
      - evawova-network
  evawova-mysql:
    image: mysql:8.0.31
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - evawova-network
  evawova-mongo:
    image: mongo:6.0.5
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: root
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - evawova-network
  evawova-redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    networks:
      - evawova-network
  evawova-app-eureka-server:
    image: evawova-app-eureka-service:latest
    ports:
      - '8761:8761'
    restart: always
    networks:
      - evawova-network
  evawova-app-admin-service:
    image: evawova-app-admin-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - evawova-mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://evawova-mysql:3306/evawova?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://evawova-app-eureka-server:8761/eureka/
    networks:
      - evawova-network

  evawova-app-performance-service:
    image: evawova-app-performance-service:latest
    ports:
      - "8081:8080"
    depends_on:
      - evawova-mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://evawova-mysql:3306/evawova?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://evawova-app-eureka-server:8761/eureka/
    networks:
      - evawova-network

  prometheus:
    image: prom/prometheus:latest
    container_name: evawova-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - evawova-network

  grafana:
    image: grafana/grafana:latest
    container_name: evawova-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - evawova-network
networks:
  evawova-network:
    driver: bridge
