version: '3.8'

services:
  evawova-zookeeper-1:
    image: confluentinc/cp-zookeeper:7.2.6
    container_name: evawova-zookeeper-1
    ports:
      - '32181:32181'
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - evawova-network

  evawova-kafka-1:
    image: confluentinc/cp-kafka:7.2.6
    container_name: evawova-kafka-1
    ports:
      - '9092:9092'
    restart: always
    depends_on:
      - evawova-zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: evawova-zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://evawova-kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - evawova-network

  evawova-kafka-2:
    image: confluentinc/cp-kafka:7.2.6
    container_name: evawova-kafka-2
    ports:
      - '9093:9093'
    restart: always
    depends_on:
      - evawova-zookeeper-1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: evawova-zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://evawova-kafka-2:29093,EXTERNAL://localhost:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - evawova-network

  evawova-kafka-3:
    image: confluentinc/cp-kafka:7.2.6
    container_name: evawova-kafka-3
    ports:
      - '9094:9094'
    restart: always
    depends_on:
      - evawova-zookeeper-1
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: evawova-zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://evawova-kafka-3:29094,EXTERNAL://localhost:9094
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - evawova-network

  evawova-kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: evawova-kafka-ui
    ports:
      - '9000:8080'
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=evawova-local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=evawova-kafka-1:29092,evawova-kafka-2:29093,evawova-evawova-kafka-3:29094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=evawova-zookeeper-1:22181
    networks:
      - evawova-network

  evawova-mysql:
    image: mysql:8.0.31
    container_name: evawova-mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    networks:
      - evawova-network

  evawova-mongo:
    image: mongo:6.0.5
    container_name: evawova-mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - evawova-network

  evawova-redis:
    image: redis:7.0
    container_name: evawova-redis
    ports:
      - '6379:6379'
    networks:
      - evawova-network

  evawova-prometheus:
    image: prom/prometheus:latest
    container_name: evawova-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - evawova-network

  evawova-grafana:
    image: grafana/grafana:latest
    container_name: evawova-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - evawova-prometheus
    networks:
      - evawova-network

  evawova-loki:
    image: grafana/loki:latest
    container_name: evawova-loki
    ports:
      - "3100:3100"
    networks:
      - evawova-network

  evawova-promtail:
    image: grafana/promtail:2.8.2
    container_name: evawova-promtail
    volumes:
      - ./promtail:/etc/promtail
      - ./logs:/logs
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - evawova-loki
    networks:
      - evawova-network

  evawova-app-eureka-server:
    image: evawova-app-eureka-service:latest
    ports:
      - '8761:8761'
    restart: always
    networks:
      - evawova-network

  evawova-app-admin-service:
    image: evawova-app-admin-service:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - evawova-mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://evawova-mysql:3306/evawova?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://evawova-app-eureka-server:8761/eureka/
      - LOG_DIR=/app/logs
    networks:
      - evawova-network

networks:
  evawova-network:
    driver: bridge
