spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://evawova-mysql:3306/evawova
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
    show-sql: true
