server:
  port: 8080
  shutdown: graceful

spring:
  config:
    import:
      - 'classpath:adapter-kafka-property.yml'
      - 'classpath:adapter-mongodb-property.yml'
      - 'classpath:adapter-persistence-property.yml'
      - 'classpath:adapter-redis-property.yml'
  application:
    name: evawova-app-admin-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://evawova-infra-evawova-app-eureka-server-1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10

logging:
  level:
    root: info
    com.evawova: debug
